### ISSUE TITLE
some issues 

### ISSUE THREAD

**Issue by stuke2** [modmore/QuickstartButtons#51] opened 2018-11-12 17:44 UTC
I made a small screencast: https://cl.ly/c519aa9ae2a3

- After making a new set, the buttons i create wont be on the new set but on the first set.
- saving doesnt close the screen, if you click multiple times on the save button, multiple buttons are created.
- i allways have to select the System Action twice, after first save, the value is not saved.

Using modx 2.6.5 and Quickstart buttons 1.3.0

**Comment by Mark-H** [comment] 2020-07-22 15:43
That's weird but I can't seem to reproduce that behavior. I'm guessing the reason it doesn't close is a validation issue on a different tab, or another error that might've gotten logged to the error log, but as it's been a while I don't expect you to still have the issue and/or those details so I'll close it. Feel free to reopen if you do have more information.

**Closed by Mark-H** 2020-07-22 15:43 UTC
